### ISSUE TITLE
WIP: provisional data model

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#10]
![19553170_10155560530254201_42865152_n](https://user-images.githubusercontent.com/16781318/27691208-40f3730a-5cdb-11e7-95fd-178e1a91e6c9.jpg)
as discussed 29/6/17:

## User
- can own business
- can own product
#### Fields
- username
- name
- password

## Business(/organisation/venue)
- can own product
- can own event
#### Fields
- name
- location
- description
- owner (required)
- accessibility

#### Fields
- name
- description

#### Fields
- name
- location
- organiser (business)

**Comment by m4v15** [comment]
### Pitfalls:

#### Permissions, adding businesses etc with different apps that have different needs:
- So nasijona and eventsApp both have very similar needs - users can have profiles with basic info (i.e. an artisan or a business/organisation) and then can create specific things attached to them (i.e. products or events)

- This seems like it should work well with easyNaz - each business/organisation could have accessibility options and then easyNaz can work pretty much as it does now but from a different database
- However, the point of easyNaz is to try and have a comprehensive list of businesses/organisations around nazareth, with their accessibility options.
- Almanarah (the app owner) were willing to do some data collection of businesses to add to the database
- This would also allow Almanarah to verify the truthfulness of the accessibility options of the businesses


But if alManarah add the organisation, who is the owner, who can edit info? Could we do it so initially if alManarah add it, they have all the permissions, but then if the actual business owner wants to get involved, permissions can be transferred?

Could alManarah have permission to edit **any** business' accessibility options?

**Comment by mattlub** [comment]
closed as more advanced discussion moved to #13
