### ISSUE TITLE
oauth authorize authenticate handler

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#115]
This dummy function needs to be implemented. It takes a request, and returns a user (if signed in) or null.

https://github.com/foundersandcoders/open-tourism-platform/blob/master/src/controllers/oauth.js#L35-L37

**Comment by m4v15** [comment]
addressed in [this commit](https://github.com/foundersandcoders/open-tourism-platform/pull/95/commits/c84f947fed8eba1e8c53ae518ce486f4bbd6b8b1)

**Comment by mattlub** [comment]
closing as was addressed in #95
