### ISSUE TITLE
create API endpoint documentation

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#12]
- CRUD endpoints for each of:
  - user
  - business (is this even the definite name?)
  - event 
  - product
  - invite
  - signup
- decide on good format: e.g.
  - github is quite good imo: https://developer.github.com/v3/repos/
  - https://bocoup.com/blog/documenting-your-api

**Comment by mattlub** [comment]
## Users
- create user
- show all users
- show specific user
- update user
- delete user

----

### Show specific user
Returns json for a specific user.
```
GET /users/:id
```

- #### URL Params (required)
`id=[integer]`

- #### Query Params
None

- #### Required Permissions
canViewUsers

- #### Success Response
**Code:** ```200```
**Content:** ```{ id : 12, name : "Michael Bloom" }```
 
- #### Error Response
**Code:** ```404 NOT FOUND```
**Content:** ```{ error : "User doesn't exist" }```

OR

**Code:** ```401 UNAUTHORIZED```
**Content:** ```{ error : "You are unauthorized to make this request." }```

- #### Sample Call

```javascript
fetch('/users/1')
```

**Comment by mattlub** [comment]
@des-des thoughts on the formatting above?
We should probably be sure about the formatting before writing out like 20 endpoints right?

**Comment by des-des** [comment]
@mattlub prob a table?

**Comment by mattlub** [comment]
closed as docs have been merged #90
