### ISSUE TITLE
Authenticating the access token

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/open-tourism-platform#121]
How are we securing the routes? 

Should they be accessible only by client's logged in with oauth, or also by people directly logged into the platform. This question affects what we do next.

The module has an authenticate function that returns the token. However this will presumably fail if a request is made that has a JWT in a cookie and no access token?

**Comment by mattlub** [comment]
close this as it was addressed?

**Comment by mattlub** [comment]
#126
