### ISSUE TITLE
document (provisional at least) db schema

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#13]
for the 4 tables:
- user
- business
- event
- product

related #10

**Comment by m4v15** [comment]
|User| |
|---|---|
|id| integer, Unique|
|username| String, Unique|
|password| String, hashed|
|email| String|
|role| String|

**Comment by m4v15** [comment]
|Business| |
|---|---|
|id| integer, Unique Key|
|ownerId| integer, foreign Key|
|name| String|
|address| String|
|category| String|
|accessOptions|String|
|openingHours|String|
|description|String|
|website|String|
|phone|Integer|
|email|String|
|imageLink|String|
|lat|float|
|lng|float|

**Comment by m4v15** [comment]
|Event| |
|---|---|
|id| integer, Unique|
|bizId| integer, foreignKey|
|name| String|
|location| String (default to Business)|
|category| String (default to Business)|
|accessOptions|String|
|startTime|String|
|endTime|String|
|date| Date|
|description|String |
|cost| String|
|imageLink|String (default to Business)|

**Comment by m4v15** [comment]
|Product| |
|---|---|
|id| integer, Unique|
|bizId| integer, foreignKey|
|name| String|
|type| String|
|description|String |
|cost| String|
|imageLink|String (default to Business)|
|numberAvaliable| integer|

**Comment by mattlub** [comment]
looks pretty good, put these into a PR so we can start to get some stuff merged?

**Comment by mattlub** [comment]
closing as inital spec merged
