### ISSUE TITLE
should OAuth access_tokens have a client associated with them?

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#143]
it's not in the [schema](https://github.com/foundersandcoders/open-tourism-platform/blob/master/src/models/auth/Token.js) but looks like it could be because of the [auth model](https://github.com/foundersandcoders/open-tourism-platform/blob/master/src/authModel.js#L54-L63)

Do we need it? I would think so but obviously it works currently without...

**Comment by mattlub** [comment]
@Karyum (from your PR #176)

so did you have to add `client` to the `Token` schema in order for refresh tokens to work?

If so you can close this issue if that gets merged.

**Comment by Karyum** [comment]
@mattlub Yeah so every time that I would try to refresh the token and the client is not provided in the `.populate` of the `getRefreshToken` function it would give me this error `{"error":"invalid_grant","error_description":"Invalid grant: refresh token is invalid"}`
im guessing it's looking through the client's object and looking through the grants array but can't find any, im not sure though.
