### ISSUE TITLE
add permissions information to API documentation

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#15]
- add specific permissions info for relevant endpoints.
- also maybe add to permissions section, a summary of each of the different permissions options

**Comment by m4v15** [comment]
Potentially get v0 going without permissions, so this could be made priority 2 or something?

**Comment by mattlub** [comment]
either
- without permissions, or
- with a single admin role which has permission to create/update/delete

@des-des @m4v15 ?

**Comment by des-des** [comment]
@mattlub @m4v15 For the initial version, we have
  1. guest (unauthenticated)
  2. member
  3. admin

There are some ownership problems around the artisan products, but I think we should ignore these for now

**Comment by mattlub** [comment]
@des-des what permissions did you have in mind for member and admin?
the way I saw it, after talking to Dan:

1. guest, unauthenticated, or basic member/user (can view businesses, events, users, add businesses)
2. business owner (can edit business they own, add events)
3. admin e.g. one of the volunteers adding businesses (can edit everything, including assign owner to business)

I'm looking forward to discussing this.
(also thoughts @m4v15?)

**Comment by m4v15** [comment]
Yeah, pretty much, except I think maybe we said guest's can't directly add business, but instead will just fill a form that sends an email to an admin (us?), who can then verify and add if legit?

**Comment by m4v15** [comment]
I'm thinking something like:

### Permissions Table
||Users|Businesses|Events|Products|
---|---|---|---|---
GET|Admin Only|Open|Open|Open|
POST|Open? Anyone can reg, defaults guest|Admin? Anyone can submit to add a business|Business owners only| Business Owners only|
PUT|Admin Only|Admin, The Specific Business Owner|Admin, Event Creator (which would be the same as the business owner)|Admin, Product Creator (again, same as BO)|
DELETE|Admin Only|Admin, The Specific Business Owner|Admin, Event Creator (which would be the same as the business owner)|Admin, Product Creator (again, same as BO)|

**Comment by m4v15** [comment]
So Users would be role based: Admin, Biz Owner, Guest.

Then, business would all have an owner field - PUT and DELETE requests would then check the users JWT to see if they are a) *A* business owner and b) that user's ID matches the id in the businesses owner field. If either fail, denied.

Similar for Events/Products PUT and DELETE. They would have a field with the ID of the business that created them. Then you can check that the user is the owner of the Business that created them.

For POST requests to events and products just need to check the user's role as a business owner and then use a JOIN or whatever to get their businesses' ID

**Comment by des-des** [comment]
Lets talk about this during the meeting

**Comment by des-des** [comment]
Okay, we have basic users:
 - Super user / owner of the open platform.
 - Admin / moderator can create any data -> can assign ownership of content
 - user - can have ownership of organisations / their data / events / products

**Comment by m4v15** [comment]
So previously, we had envisioned that business would have to own events, or businesses would have to own products.

However we now think that's a bit too limiting and is for no real reason apart from how some of the apps work.

Instead, any registered user can:

- create a business
- create an event
- create a product

Business do not have to have owners and equally events/product do not have to have businesses, these are optional (fields in the tables would link them)

moderators can:

- assign owners to businesses after manual verification
- edit any of the information in the database, apart from user table.

Super Users can:

- do everything, including edit user table.

**Comment by m4v15** [comment]
Question re: edit permissions for different fields in the tables - different roles can edit different fields in tables

**Comment by mattlub** [comment]
Updated API permissions table:
![fullsizerender](https://user-images.githubusercontent.com/16781318/27856213-1247a586-6176-11e7-82c6-f62aff11bef7.jpg)

Businesses, Events, Products are all open access and can be created by anyone registered user.

**Comment by mattlub** [comment]
closing as permissions are partially documented now and #160
