### ISSUE TITLE
heroku hosting

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#156]
This is currently being hosted on my Heroku account, does FAC have a Heroku account we could transfer it to?

If not, should we make one?

**Comment by sofer** [comment]
@matt we don't have an organisation Heroku account (too expensive), but we do currently have a couple of FAC apps hosted on dan@foundersandcoders.com. you could add that account as a collaborator on the app--and transfer ownership when ready.

**Comment by Karyum** [comment]
@mattlub me and @des-des moved the app to a different user that we bought hosting for

**Comment by des-des** [comment]
Heroku account at opentourismplatform@gmail.com
