### ISSUE TITLE
document the signup flow

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#16]
i.e. the invite system etc.

**Comment by m4v15** [comment]
Basic:
1. Admin goes to /invite with invitee's email address as a param?
    - GET /invite goes to page with check boxes or params which decide what kind of user you are inviting them to become
    - POST /invite?params sends the invite
2. Sends invite to said email address with link containing JWT
3. Link leads to custom sign up (/signup) page depending on what was specified in the invite?
4. When filled in, POST /adduser or something, which will add that person to user table with whatever role is specified

? @mattlub

**Comment by mattlub** [comment]
closing as outdated.
