### ISSUE TITLE
check User owns resource throws 500 when resource doesn't have owner

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/open-tourism-platform#162]
Sort of an edge case but also with Data Entry it is likely a lot of resources might be made without owners initially

**Comment by m4v15** [comment]
**Moved to it's own issue, left here for record sake**
Additionally, if the resource Id searched for is invalid it now gets thrown [here (when the trying to access the resource to identify the owner)](https://github.com/foundersandcoders/open-tourism-platform/blob/master/src/helpers/permissions.js#L48) so it doesn't throw an unauthorised error, even if the user is unauthorised (as this happens before it is certain if the user is authed or not).

This is not a big deal (or a deal at all?), but just got confusing with the tests for a bit

**Comment by mattlub** [comment]
oops
