### ISSUE TITLE
automatically verify content for non `BASIC` users

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/open-tourism-platform#185]
when someone is adding content to the api and is not a `BASIC` user it should update the content automatically to `verified: true`, so that they don't go through verifying the content.

**Comment by mattlub** [comment]
also need to automatically set `verified: false` for non `ADMIN` or `SUPER` users, because currently you could include `verified: true` in the body of a `POST` request

**Comment by Karyum** [comment]
@mattlub im trying to figure out what is the reason that creating content is literally open for everyone, ( open tourism platform yeah :wink: ik ) but you would atleast ask them to be a user. so im not sure whats the reason behind this ?

**Comment by Karyum** [comment]
what is stopping me right now from making a script and bombarding the otp with loads of content ? 

*will not do that no worries :laughing:*
