### ISSUE TITLE
Planning meeting - July 2 at 13:00

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/open-tourism-platform#19]
@hibaakel @RQ16 @Suuuuha @Karyum @MohamedOmarii @HilbertSpitzer 

Since tomorrow (Sunday) is the only day you will all be in attendance, I suggest we meet at lunch to discuss the plan for the Open Tourism Platform. 

@sofer will explain:
- Overall plan
- Individual assignments
- Schedule
- Budget
- Invoicing

For more, visit this document: https://docs.google.com/document/d/1vt7LdZOgEqx6nuxWDCnvDHL8qVWaln4MkHGdTglKcX4/edit?usp=sharing

**Comment by mattlub** [comment]
closed as meeting minutes added
