### ISSUE TITLE
Data entry screens

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/open-tourism-platform#20]
We need generic user authentication and data entry screens in order to allow us to begin to sign up businesses and populate the database.

Volunteers are scheduled to be available to work with business owners to sign them up as users and to enter content from august 1.

**Comment by des-des** [comment]
@sofer I see another way of adding data. The apps build on top of the platform would modify data using a rest api. I think we need to be careful of not trying to build wikipedia for Nazareth.

We do not want to get drawn into building some massive platform that includes everybody's different ideas (ie Nazareth info). Do we not want to focus on building a data platform that other apps can use?

**Comment by des-des** [comment]
@sofer, we want to make sure the platform can meet the requirements of the 4 apps we build.

  > sign up businesses and populate the database.

What app are you thinking of here? How is this data going to be displayed?

**Comment by sofer** [comment]
@des-des you are almost certainly right about the need to meet the needs of the apps we already have first and to avoid over-generalising the potential use cases, but I am keen to separate the dependency of initial data entry from having the apps ready to go. 

The constraint I am concerned about is that we will have volunteers ready to go and meet business owners and help them get on the platform to input their details from August 1st. That is a tighter timescale than we need for the launch of the apps. It would be useful to remove that dependency. 

Hence the thinking around some simple data entry screens to allow us to populate the database in advance of the apps actually being ready.

However, I am not entirely sold on this approach and can very easily be persuaded to drop it.

**Comment by des-des** [comment]
@sofer no it sounds good,

But we do need to make sure these screens meet the requirements of the apps

**Comment by mattlub** [comment]
Would we consider a data entry interface 'app' as the first app built on top of the platform, so we could use it for initial data entry and potentially stop it at some point if it were no longer needed?

**Comment by des-des** [comment]
@mattlub 

Spot on. I agree, We will create a separate repo also, this also gives us the opportunity to properly test the api we will built

**Comment by mattlub** [comment]
@sofer can we close this now the data entry app is in progress?
