### ISSUE TITLE
Timelines

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/open-tourism-platform#23]
Thursday 7th June 10AM GMT - Go thought requirements and spec
Friday 8th June AM/PM decide on stack and backlog of technical tasks with with time estimates
Friday 8th 4PM GMT sprint planning
Sunday 10th AM sprint 1 starts!

**Comment by m4v15** [comment]
So Thursday's the 6th, but also, we thought:

**Wednesday** 5th June 10AM GMT - Go thought requirements and spec
**Thursday** 6th June AM/PM decide on stack and backlog of technical tasks with with time estimates
Friday 7th 4PM GMT sprint planning
Sunday 10th AM sprint 1 starts!

**Comment by des-des** [comment]
Sounds good

**Comment by m4v15** [comment]
The Nazareth Facilitator stand up involving Jen and Elias has been moved to 12 tomorrow (Naz time), can we push ours back to 12:30? Soz.

**Comment by mattlub** [comment]
closing because old.
