### ISSUE TITLE
Build Mongo schema

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#25]
- [x] Finalise db fields (should be finalised by sprint start)
- Create collections including their individual requirements
  - [x] Users T2h
  - [x] Places T2h
  - [x] Events T2h
  - [x] Products T2h

**Comment by m4v15** [comment]
Did we decide on a multi-language approach?

atm we haven't done extra columns, they should be easy enough to add in the future though, right @des-des, @mantagen

**Comment by des-des** [comment]
@m4v15 yeah, I think its better to build this up slowly, so do not worry to much about this right now
