### ISSUE TITLE
should we have a 'places' table in the db?

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#30]
- I know this may not be required for the initial 4 apps.
- But I can see it being important for tourism.
- e.g. the Basilica would not fit anywhere in the currently proposed data model.

Thoughts?

**Comment by sofer** [comment]
Also, Hospitals, schools, libraries...

If you go for both "places" and "businesses", you might have to introduce another relationship in the schema ("a business has_many locations"). Not sure if that is necessary. Perhaps it is just a question of naming conventions.

**Comment by mantagen** [comment]
Could be useful 
https://docs.mongodb.com/manual/geospatial-queries/

**Comment by des-des** [comment]
@sofer right now we are allowing an organisation / business to sign up as a user, this leaves us space to to grow out the idea of having orgs in the future, without having to deal with all that complexity up front

**Comment by mattlub** [comment]
closing as initial specs now merged.
