### ISSUE TITLE
deploy to heroku

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#36]
relates #32

**Comment by mattlub** [comment]
I've put it on heroku with a mongolab db, https://dashboard.heroku.com/apps/nazareth-open-tourism-platform

**Comment by m4v15** [comment]
Can you give me permission to view plz

**Comment by mattlub** [comment]
closed as it's now LIVE

**Comment by mattlub** [comment]
@des-des @mantagen @m4v15  @sofer it's on my heroku account right now, I can give you all collaborator status or we can transfer it elsewhere at some point.

**Comment by des-des** [comment]
@mattlub That great for now, we will work out what to do with it next sprint
