### ISSUE TITLE
Initial requirement gathering

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/open-tourism-platform#4]
Okay, there are 4 apps we already know we will build on top of this platform.

Going through these would be a good place to start in terms of requirement gathering.
 
We already have MVPs:

 - [x] [Nasijona](https://github.com/FACN1/Nasijona) #7
 - [x] [easyNaz](https://github.com/FACN1/easyNaz) #6
 - [x] [PAS](https://github.com/FACN1/PAS-MVP) #8
 - [x] [nazareth-events](https://github.com/FACN1/nazareth-events) #9

**Comment by des-des** [comment]
The next steps,

  1. Go through each repo, create a short doc (each in its own issue). In it
     1. Aims of project
     2. One sentence description of project
     3. Requirements of backend, for next iteration.
  2. Chase up developers who worked on all 4 projects, to complete these documents.
  3. Decide initial technical requirement
  4. Decide architecture
  5. Design API
  6. Implementation

**Comment by mattlub** [comment]
provisionally done step 1, need to chase up some of the others now.
