### ISSUE TITLE
set up test folder structure

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/open-tourism-platform#47]
and test script in package.json, using tape and supertest, add coverage with istanbul, integrate with Travis

relates #26

**Comment by m4v15** [comment]
@des-des @mantagen do we want to set up test/development databases to be running our tests on/messing around with when developing?

**Comment by des-des** [comment]
@m4v15 guessing we cleared up that question in yesterdays standup?

**Comment by m4v15** [comment]
@des-des yes, cheers.

New question - we can't access the settings to add travis intergration - who is the owner of this repo? @sofer?

**Comment by m4v15** [comment]
Done :shipit:
