### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/open-tourism-platform#70]
We should have done these really:

- [x] adding something with the wrong category
- [x] checking the foreign key (ownerID and placeID) fields in places/products/events db

**Comment by des-des** [comment]
@m4v15 shall I move this to sprint 3 or backlog?

**Comment by mattlub** [comment]
backlog it.

**Comment by mattlub** [comment]
@m4v15 can you clarify the second checkbox? (or close?)
