### ISSUE TITLE
Create error handling middleware

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/open-tourism-platform#71]
- [x] create middleware for error handling
   - [x] add basic middleware
   - [x] add if statements to deal with most common errors
      - [x] invalid id
      - [x] validation errors
      - [x] no id found in database
        - [x] add static methods to the schemas to error when id is not found (atm it just returns null)
      - [x] fails unique constraint
      - [x] don't hard code in the error codes or names, have a JSON somewhere.
 - [x] test the middleware
 - [x] refactor old code
   - [x] pass ```next``` to each route, call it on the ```catch```
   - [ ] loose some of the tests

**Comment by des-des** [comment]
@m4v15 @mattlub is there anything outstanding on this?

**Comment by m4v15** [comment]
No, all done. We could I guess lose some tests, but I (we) think they're good integration tests (in the controllers file)
