### ISSUE TITLE
Write docs for Signup / Login

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/open-tourism-platform#72]
- [x] Work out how we do this
 - [ ] Write docs

**Comment by m4v15** [comment]
## Update
---
- We have begun implementing this during auth/session implementation (#95)

We are running and OAuth2 server, meaning both users and apps can access/change the database, depending on users scopes.

Flow with regards to users:
1. Anyone goes to /register
2. Anyone can then register and login, with role defaulting to BASIC
3. Super users can then change user roles

Flow with regards to apps:
1. Super User can add apps using postman, apps have id and code
2. Apps can then use the OAuth2 server and user authorisations to access the database

**Comment by des-des** [comment]
closing, task moved to #103
