### ISSUE TITLE
finalise the fixed categories

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/open-tourism-platform#82]
**Edit by @mattlub**

We are trying to finalise the fixed categories, can people please suggest any they think should be added:
@RQ16 @JWLD @Karyum @Suuuuha @MohamedOmarii @philawsophizing @m4v15 @des-des @mantagen Thanks

[current suggested categories here](https://github.com/foundersandcoders/open-tourism-platform/blob/finalise-db-fields/src/models/constants.json) or below:

### Accessibility options
  - Audio Recordings
  - Braille
  - Big Fonts
  - Carer
  - Place for Guide Dog
  - SMS messaging
  - Sign Language
  - Good Lighting
  - Carer
  - WheelChair Access
  - Disabled Parking
  - Disabled Toilets
  - Carer
### Place Categories
  - cafe
  - music venue
  - religious site
  - food and drink
  - education
  - retail
  - sport
  - municipal
  - healthcare

### Event Categories
  - music
  - dining
  - educational
  - conference
  - sport
  - competition
  - launch
  - party
  - wedding
  - cultural event
  - miscellaneous-

### Product Categories
  - jewellery
  - clothing
  - crochet
  - calligraphy
  - embroidery
  - metalwork
  - food
  - drink
  - pottery
  - glassware
---
**Edit**:
We need to decide on the fixed categories for `roles`, `events`, `products`, `accessibility`.

Can work with current/previous app developers on this

Original
---
We need to finalise these before v1

**Comment by mattlub** [comment]
is this done? docs link to the [constants file](https://github.com/foundersandcoders/open-tourism-platform/blob/master/src/models/constants.json).

Or maybe change the title of the issue to be "finalise the fixed categories" or similar?

UPDATE: mavis updated the title
