### ISSUE TITLE
Apps scheduling meeting notes - July 27

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/open-tourism-platform#83]
1. Platform update + plans for next sprint

Docs will be done by end of the day and then should be ready to start playing with by Sunday morning: Restful CRUD routes: users, products, events, places, multi-language support is partial. 

Next up: /en and /ar support. Login, signup and role-based authorisation; event logging.

2. Project priorities
- Data entry
- Events
- the rest

3. Project roles
- One or two developers
- One QA
- One scrum master
- One PO

4. Pay
- Through NCTA
- Minimum wage (₪26.88 per hour)
- Please keep track of actual hours worked (use [toggl](https://toggl.com/))
- Fill in [this spreadsheet](https://docs.google.com/spreadsheets/d/1b-dIuX8tzhqVIfmBh_3QT0Q260xrE1bEfMdmiaY7mB8/edit#gid=853263495)

5. Availability
- Dev  @RQ16 - available until mid-October
- Dev @MohamedOmarii  - 4 days/wk until end sept
- QA - @esraajb, @shiryz, @m4v15 @mattlub @JWLD, Meta-QA: @des-des 
- Scrum Master - @mattlub @mattlub @JWLD @shiryz?
- PO: @des-des or me for data entry, 

Follow up on resourcing: @m4v15 and me today, 5pm Jerusalem time

**Comment by m4v15** [comment]
Shall we put this in a doc somewhere and close this issue?

**Comment by des-des** [comment]
@m4v15 if in a doc should not be in this repo i think, keeping this kinda meta stuff in issues fine but not in git history

**Comment by mattlub** [comment]
@des-des we have minutes from a couple of meetings in this repo, should we remove?

**Comment by des-des** [comment]
@mattlub 
I think notes that are specify to the code / platform are fine, but stuff like finance maybe lives somewhere else
