### ISSUE TITLE
OAuth set up

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/open-tourism-platform#93]
Trying to build an Oauth2 server, using https://github.com/oauthjs/node-oauth2-server/

relates #27 #92 

- [x] build the necessary functions following the docs [here](https://oauth2-server.readthedocs.io/en/latest/model/spec.html) and help from [this guy](https://tech.zilverline.com/2017/03/17/nodejs-oauth2-provider)
- [x] need to register clients on the platform (apps) will be done by SUPER
- [x] need to register users on the platform (people) #95 
- [x] then need to try the module and function pattern and get it working

**Comment by m4v15** [comment]
[This looks helpful also](http://scottksmith.com/blog/2014/07/02/beer-locker-building-a-restful-api-with-node-oauth2-server/)

**Comment by m4v15** [comment]
Can this be closed?

**Comment by mattlub** [comment]
yep. close and I will create another issue about what was missing from the OAuth branch that got merged.
