### ISSUE TITLE
DB Field naming conventions

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#96]
In [this PR](https://github.com/foundersandcoders/open-tourism-platform/pull/94) I am populating the `placeId` field in the `events` model

**I want to change the field name in the events model to `place` instead of `placeId`**
- I would also propose to do the same on all fields which currently end in `'id'`, even if we do not plan to populate them.

The potential problems with this is confusion:
- this would mean on `POST`, you would have to send an `id` under the `place` field

------

@des-des mentioned the possibility of sending it back as `place` when populated, but keeping the db field as `placeId`. The problem here is seeming inconsistency in the model between a `POST` and a `GET`. Does anyone do this?

Thoughts? @m4v15 @des-des @mantagen

**Comment by mattlub** [comment]
I am leaning towards @des-des suggestion now to be honest.

**Comment by des-des** [comment]
Yeah this is a really good question that I do not have an answer to. Maybe @mantagen has some thoughts. I think if you are on the fence, go for the path of least resistance.. ?

**Comment by m4v15** [comment]
Yeah my whole issue with it was that in the DB it's just an id not a place itself, I'm pro calling it place id in the DB models but in the response object call it place. I see what you mean about the `POST` issue, but I don't think it's a massive problem - however you probably have more of an idea of this due doing stuff with Mohamed on the events app.

**Comment by m4v15** [comment]
Although I guess by path of least resistance the easier thing would be to just call it place. Tbh I can also be convinced easily either way

**Comment by mantagen** [comment]
In the DB it's not just an id. It's a populatable reference to an entity, called a _place_.

... I'd probably go with `place`

**Comment by mattlub** [comment]
I think this is agreed, we will remove all appended `id`
