### ISSUE TITLE
No 'Access-Control-Allow-Access' header is present

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#98]
@MohamedOmarii can't get data from the `/events` endpoint when working on nazareth-events

![screen shot 2017-08-14 at 12 27 10](https://user-images.githubusercontent.com/16781318/29266044-f26fa39a-80eb-11e7-9c9e-786e50ba40e0.png)

**Comment by mattlub** [comment]
https://stackoverflow.com/questions/7067966/how-to-allow-cors

**Comment by MohamedOmarii** [comment]
Yes I have in google chrome `cros` , it was working but now it isn't 
I have to use it in express

**Comment by MohamedOmarii** [comment]
I used `cors` at first was working , now is not working

**Comment by mattlub** [comment]
closed as it's fixed now
